import { ASSISTANT_MUTATION_TOOL_NAME } from '../../../shared/assistant-actions.js'

export const ASSISTANT_TOOL_NAMES = [ASSISTANT_MUTATION_TOOL_NAME] as const

export function buildAssistantToolMap(): Record<string, boolean> {
    return {
        [ASSISTANT_MUTATION_TOOL_NAME]: true,
    }
}

function buildAssistantMutationToolContent() {
    return [
        'import { tool } from "@opencode-ai/plugin"',
        '',
        'const RESERVED_ROOT_PATHS = new Set(["SKILL.md", "draft.json"])',
        '',
        'function isRecord(value) {',
        '  return !!value && typeof value === "object" && !Array.isArray(value)',
        '}',
        '',
        'function isNonEmptyString(value) {',
        '  return typeof value === "string" && value.trim().length > 0',
        '}',
        '',
        'function normalizeOptionalString(value, options) {',
        '  if (typeof value === "string") {',
        '    const trimmed = value.trim()',
        '    return trimmed ? trimmed : undefined',
        '  }',
        '  if (options?.allowNull && value === null) return null',
        '  return value === undefined ? undefined : value',
        '}',
        '',
        'function normalizeOptionalStringArray(value) {',
        '  if (!Array.isArray(value)) return value === undefined ? undefined : value',
        '  return value.map((entry) => (typeof entry === "string" ? entry.trim() : entry)).filter((entry) => entry !== "")',
        '}',
        '',
        'function normalizeDraftBlueprintCandidate(value) {',
        '  if (!isRecord(value)) return value === undefined ? undefined : value',
        '  const normalizedTags = normalizeOptionalStringArray(value.tags)',
        '  const normalized = {',
        '    ...(normalizeOptionalString(value.ref) !== undefined ? { ref: normalizeOptionalString(value.ref) } : {}),',
        '    ...(normalizeOptionalString(value.name) !== undefined ? { name: normalizeOptionalString(value.name) } : {}),',
        '    ...(normalizeOptionalString(value.content) !== undefined ? { content: normalizeOptionalString(value.content) } : {}),',
        '    ...(normalizeOptionalString(value.slug) !== undefined ? { slug: normalizeOptionalString(value.slug) } : {}),',
        '    ...(normalizeOptionalString(value.description) !== undefined ? { description: normalizeOptionalString(value.description) } : {}),',
        '    ...(Array.isArray(normalizedTags) && normalizedTags.length > 0 ? { tags: normalizedTags } : {}),',
        '    ...(value.openEditor === true ? { openEditor: true } : {}),',
        '  }',
        '  return Object.keys(normalized).length === 0 ? undefined : normalized',
        '}',
        '',
        'function hasMeaningfulDraftBlueprint(value) {',
        '  return isRecord(normalizeDraftBlueprintCandidate(value))',
        '}',
        '',
        'function normalizeModelBlueprintCandidate(value) {',
        '  if (!isRecord(value)) return value === undefined || value === null ? value : value',
        '  const provider = normalizeOptionalString(value.provider)',
        '  const modelId = normalizeOptionalString(value.modelId)',
        '  if (!provider && !modelId) return undefined',
        '  return {',
        '    ...(provider !== undefined ? { provider } : {}),',
        '    ...(modelId !== undefined ? { modelId } : {}),',
        '  }',
        '}',
        '',
        'function normalizeRelationBlueprintCandidate(value) {',
        '  if (!isRecord(value)) return value === undefined ? undefined : value',
        '  return {',
        '    ...value,',
        '    sourceParticipantKey: normalizeOptionalString(value.sourceParticipantKey),',
        '    sourcePerformerId: normalizeOptionalString(value.sourcePerformerId),',
        '    sourcePerformerRef: normalizeOptionalString(value.sourcePerformerRef),',
        '    sourcePerformerName: normalizeOptionalString(value.sourcePerformerName),',
        '    targetParticipantKey: normalizeOptionalString(value.targetParticipantKey),',
        '    targetPerformerId: normalizeOptionalString(value.targetPerformerId),',
        '    targetPerformerRef: normalizeOptionalString(value.targetPerformerRef),',
        '    targetPerformerName: normalizeOptionalString(value.targetPerformerName),',
        '    name: normalizeOptionalString(value.name),',
        '    description: normalizeOptionalString(value.description),',
        '  }',
        '}',
        '',
        'function normalizePerformerActionCandidate(action) {',
        '  const normalizedTalDraftId = normalizeOptionalString(action.talDraftId)',
        '  const normalizedTalDraftRef = normalizeOptionalString(action.talDraftRef)',
        '  const normalizedTalDraft = normalizeDraftBlueprintCandidate(action.talDraft)',
        '  const normalizedTalUrn = normalizeOptionalString(action.talUrn, { allowNull: true })',
        '  return {',
        '    ...action,',
        '    model: normalizeModelBlueprintCandidate(action.model),',
        '    modelVariant: normalizeOptionalString(action.modelVariant, { allowNull: true }),',
        '    description: normalizeOptionalString(action.description, { allowNull: true }),',
        '    talUrn: normalizedTalUrn === null && (',
        '      isNonEmptyString(normalizedTalDraftId)',
        '      || isNonEmptyString(normalizedTalDraftRef)',
        '      || hasMeaningfulDraftBlueprint(normalizedTalDraft)',
        '    ) ? undefined : normalizedTalUrn,',
        '    talDraftId: normalizedTalDraftId,',
        '    talDraftRef: normalizedTalDraftRef,',
        '    talDraft: normalizedTalDraft,',
        '    addDanceUrns: normalizeOptionalStringArray(action.addDanceUrns),',
        '    addDanceDraftIds: normalizeOptionalStringArray(action.addDanceDraftIds),',
        '    addDanceDraftRefs: normalizeOptionalStringArray(action.addDanceDraftRefs),',
        '    addDanceDrafts: Array.isArray(action.addDanceDrafts)',
        '      ? action.addDanceDrafts.map((draft) => normalizeDraftBlueprintCandidate(draft)).filter((draft) => draft !== undefined)',
        '      : action.addDanceDrafts,',
        '    removeDanceUrns: normalizeOptionalStringArray(action.removeDanceUrns),',
        '    removeDanceDraftIds: normalizeOptionalStringArray(action.removeDanceDraftIds),',
        '    addMcpServerNames: normalizeOptionalStringArray(action.addMcpServerNames),',
        '    removeMcpServerNames: normalizeOptionalStringArray(action.removeMcpServerNames),',
        '  }',
        '}',
        '',
        'function normalizeAssistantActionCandidate(action) {',
        '  if (!isRecord(action) || !isNonEmptyString(action.type)) return action',
        '  switch (action.type) {',
        '    case "createPerformer":',
        '    case "updatePerformer":',
        '      return normalizePerformerActionCandidate(action)',
        '    case "createAct":',
        '      return {',
        '        ...action,',
        '        description: normalizeOptionalString(action.description),',
        '        actRules: normalizeOptionalStringArray(action.actRules),',
        '        participantPerformerIds: normalizeOptionalStringArray(action.participantPerformerIds),',
        '        participantPerformerRefs: normalizeOptionalStringArray(action.participantPerformerRefs),',
        '        participantPerformerNames: normalizeOptionalStringArray(action.participantPerformerNames),',
        '        relations: Array.isArray(action.relations)',
        '          ? action.relations.map((relation) => normalizeRelationBlueprintCandidate(relation)).filter((relation) => relation !== undefined)',
        '          : action.relations,',
        '      }',
        '    case "connectPerformers":',
        '      return normalizeRelationBlueprintCandidate(action)',
        '    default:',
        '      return action',
        '  }',
        '}',
        '',
        'function normalizeAssistantActionEnvelope(envelope) {',
        '  if (!isRecord(envelope) || !Array.isArray(envelope.actions)) return envelope',
        '  return {',
        '    ...envelope,',
        '    actions: envelope.actions.map((action) => normalizeAssistantActionCandidate(action)),',
        '  }',
        '}',
        '',
        'function normalizeAssistantBundlePath(value) {',
        '  if (typeof value !== "string") return null',
        '  const normalized = value.trim().replace(/\\\\/g, "/").replace(/^\\.\\/+/, "")',
        '  if (!normalized || normalized.includes("\\\\0")) return null',
        '  if (normalized.startsWith("/") || /^[a-zA-Z]:\\//.test(normalized)) return null',
        '  const parts = normalized.split("/").filter(Boolean)',
        '  if (parts.length === 0) return null',
        '  if (parts.some((part) => part === "." || part === "..")) return null',
        '  const joined = parts.join("/")',
        '  if (RESERVED_ROOT_PATHS.has(joined)) return null',
        '  return joined',
        '}',
        '',
        'function pushIssue(issues, level, actionIndex, message) {',
        '  issues.push({ level, actionIndex, message })',
        '}',
        '',
        'function registerNamedRef(issues, actionIndex, refs, namespace, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  if (refs.has(value)) {',
        '    pushIssue(issues, "error", actionIndex, `${namespace} ref "${value}" is declared more than once in the same tool call.`)',
        '    return',
        '  }',
        '  refs.add(value)',
        '}',
        '',
        'function registerDraftRef(issues, actionIndex, refs, kind, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  const existingKind = refs.get(value)',
        '  if (existingKind) {',
        '    pushIssue(issues, "error", actionIndex, `draft ref "${value}" is already declared for a ${existingKind} draft earlier in the same tool call.`)',
        '    return',
        '  }',
        '  refs.set(value, kind)',
        '}',
        '',
        'function requireNamedRef(issues, actionIndex, refs, namespace, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  if (!refs.has(value)) {',
        '    pushIssue(issues, "error", actionIndex, `${namespace} ref "${value}" is used before it is created in the same tool call.`)',
        '  }',
        '}',
        '',
        'function requireDraftRef(issues, actionIndex, refs, kind, value) {',
        '  if (!isNonEmptyString(value)) return',
        '  const existingKind = refs.get(value)',
        '  if (!existingKind) {',
        '    pushIssue(issues, "error", actionIndex, `${kind} draft ref "${value}" is used before it is created in the same tool call.`)',
        '    return',
        '  }',
        '  if (existingKind !== kind) {',
        '    pushIssue(issues, "error", actionIndex, `${kind} draft ref "${value}" resolves to a ${existingKind} draft in the same tool call.`)',
        '  }',
        '}',
        '',
        'function lintPerformerFields(actionIndex, fields, refState, issues) {',
        '  const talSelectorCount = [',
        '    isNonEmptyString(fields.talUrn) || fields.talUrn === null,',
        '    isNonEmptyString(fields.talDraftId),',
        '    isNonEmptyString(fields.talDraftRef),',
        '    hasMeaningfulDraftBlueprint(fields.talDraft),',
        '  ].filter(Boolean).length',
        '  if (talSelectorCount > 1) {',
        '    pushIssue(issues, "error", actionIndex, "Performer actions must choose only one Tal source among talUrn, talDraftId, talDraftRef, or talDraft.")',
        '  }',
        '  requireDraftRef(issues, actionIndex, refState.drafts, "tal", fields.talDraftRef)',
        '  if (Array.isArray(fields.addDanceDraftRefs)) {',
        '    for (const draftRef of fields.addDanceDraftRefs) {',
        '      requireDraftRef(issues, actionIndex, refState.drafts, "dance", draftRef)',
        '    }',
        '  }',
        '}',
        '',
        'function lintRelationRefs(actionIndex, relation, refState, issues) {',
        '  requireNamedRef(issues, actionIndex, refState.performers, "performer", relation.sourcePerformerRef)',
        '  requireNamedRef(issues, actionIndex, refState.performers, "performer", relation.targetPerformerRef)',
        '}',
        '',
        'function registerInlineDraftRefs(actionIndex, fields, refState, issues) {',
        '  if (hasMeaningfulDraftBlueprint(fields.talDraft)) {',
        '    registerDraftRef(issues, actionIndex, refState.drafts, "tal", fields.talDraft.ref)',
        '  }',
        '  if (Array.isArray(fields.addDanceDrafts)) {',
        '    for (const draft of fields.addDanceDrafts) {',
        '      if (isRecord(draft)) {',
        '        registerDraftRef(issues, actionIndex, refState.drafts, "dance", draft.ref)',
        '      }',
        '    }',
        '  }',
        '}',
        '',
        'function lintAssistantActionEnvelope(envelope) {',
        '  const refState = { performers: new Set(), acts: new Set(), drafts: new Map() }',
        '  const issues = []',
        '  for (const [actionIndex, action] of envelope.actions.entries()) {',
        '    switch (action.type) {',
        '      case "createTalDraft":',
        '        registerDraftRef(issues, actionIndex, refState.drafts, "tal", action.ref)',
        '        break',
        '      case "updateTalDraft":',
        '      case "deleteTalDraft":',
        '        requireDraftRef(issues, actionIndex, refState.drafts, "tal", action.draftRef)',
        '        break',
        '      case "createDanceDraft":',
        '        registerDraftRef(issues, actionIndex, refState.drafts, "dance", action.ref)',
        '        break',
        '      case "updateDanceDraft":',
        '      case "deleteDanceDraft":',
        '      case "upsertDanceBundleFile":',
        '      case "deleteDanceBundleEntry":',
        '        requireDraftRef(issues, actionIndex, refState.drafts, "dance", action.draftRef)',
        '        break',
        '      case "createPerformer":',
        '        lintPerformerFields(actionIndex, action, refState, issues)',
        '        registerNamedRef(issues, actionIndex, refState.performers, "performer", action.ref)',
        '        registerInlineDraftRefs(actionIndex, action, refState, issues)',
        '        break',
        '      case "updatePerformer":',
        '        requireNamedRef(issues, actionIndex, refState.performers, "performer", action.performerRef)',
        '        lintPerformerFields(actionIndex, action, refState, issues)',
        '        registerInlineDraftRefs(actionIndex, action, refState, issues)',
        '        break',
        '      case "deletePerformer":',
        '        requireNamedRef(issues, actionIndex, refState.performers, "performer", action.performerRef)',
        '        break',
        '      case "createAct": {',
        '        const participantCount = (action.participantPerformerRefs?.length || 0) + (action.participantPerformerIds?.length || 0) + (action.participantPerformerNames?.length || 0)',
        '        if ((action.relations?.length || 0) === 0 && participantCount >= 2) {',
        '          pushIssue(issues, "warning", actionIndex, "createAct has multiple participants but no relations. This often produces a disconnected workflow.")',
        '        }',
        '        for (const performerRef of action.participantPerformerRefs || []) {',
        '          requireNamedRef(issues, actionIndex, refState.performers, "performer", performerRef)',
        '        }',
        '        for (const relation of action.relations || []) {',
        '          lintRelationRefs(actionIndex, relation, refState, issues)',
        '        }',
        '        registerNamedRef(issues, actionIndex, refState.acts, "act", action.ref)',
        '        break',
        '      }',
        '      case "updateAct":',
        '      case "deleteAct":',
        '        requireNamedRef(issues, actionIndex, refState.acts, "act", action.actRef)',
        '        break',
        '      case "attachPerformerToAct":',
        '      case "detachParticipantFromAct":',
        '      case "updateParticipantSubscriptions":',
        '        requireNamedRef(issues, actionIndex, refState.acts, "act", action.actRef)',
        '        requireNamedRef(issues, actionIndex, refState.performers, "performer", action.performerRef)',
        '        if (action.type === "updateParticipantSubscriptions" && isRecord(action.subscriptions)) {',
        '          for (const performerRef of action.subscriptions.messagesFromPerformerRefs || []) {',
        '            requireNamedRef(issues, actionIndex, refState.performers, "performer", performerRef)',
        '          }',
        '        }',
        '        break',
        '      case "connectPerformers":',
        '        requireNamedRef(issues, actionIndex, refState.acts, "act", action.actRef)',
        '        lintRelationRefs(actionIndex, action, refState, issues)',
        '        break',
        '      case "updateRelation":',
        '      case "removeRelation":',
        '        requireNamedRef(issues, actionIndex, refState.acts, "act", action.actRef)',
        '        break',
        '      default:',
        '        break',
        '    }',
        '  }',
        '  return issues',
        '}',
        '',
        'const stringArray = tool.schema.array(tool.schema.string())',
        'const optionalStringArray = stringArray.optional()',
        'const draftBlueprintSchema = tool.schema.object({',
        '  ref: tool.schema.string().optional(),',
        '  name: tool.schema.string(),',
        '  content: tool.schema.string(),',
        '  slug: tool.schema.string().optional(),',
        '  description: tool.schema.string().optional(),',
        '  tags: optionalStringArray,',
        '  openEditor: tool.schema.boolean().optional(),',
        '})',
        'const modelBlueprintSchema = tool.schema.object({',
        '  provider: tool.schema.string(),',
        '  modelId: tool.schema.string(),',
        '})',
        'const subscriptionsSchema = tool.schema.object({',
        '  messagesFromParticipantKeys: optionalStringArray,',
        '  messagesFromPerformerIds: optionalStringArray,',
        '  messagesFromPerformerRefs: optionalStringArray,',
        '  messagesFromPerformerNames: optionalStringArray,',
        '  messageTags: optionalStringArray,',
        '  callboardKeys: optionalStringArray,',
        '  eventTypes: tool.schema.array(tool.schema.literal("runtime.idle")).optional(),',
        '})',
        'const safetySchema = tool.schema.object({',
        '  maxEvents: tool.schema.number().finite().nonnegative().optional(),',
        '  maxMessagesPerPair: tool.schema.number().finite().nonnegative().optional(),',
        '  maxBoardUpdatesPerKey: tool.schema.number().finite().nonnegative().optional(),',
        '  quietWindowMs: tool.schema.number().finite().nonnegative().optional(),',
        '  threadTimeoutMs: tool.schema.number().finite().nonnegative().optional(),',
        '  loopDetectionThreshold: tool.schema.number().finite().nonnegative().optional(),',
        '})',
        'const relationBlueprintSchema = tool.schema.object({',
        '  sourceParticipantKey: tool.schema.string().optional(),',
        '  sourcePerformerId: tool.schema.string().optional(),',
        '  sourcePerformerRef: tool.schema.string().optional(),',
        '  sourcePerformerName: tool.schema.string().optional(),',
        '  targetParticipantKey: tool.schema.string().optional(),',
        '  targetPerformerId: tool.schema.string().optional(),',
        '  targetPerformerRef: tool.schema.string().optional(),',
        '  targetPerformerName: tool.schema.string().optional(),',
        '  direction: tool.schema.enum(["both", "one-way"]).optional(),',
        '  name: tool.schema.string(),',
        '  description: tool.schema.string(),',
        '})',
        'const performerFieldsSchema = {',
        '  model: modelBlueprintSchema.nullable().optional(),',
        '  modelVariant: tool.schema.string().nullable().optional(),',
        '  description: tool.schema.string().nullable().optional(),',
        '  talUrn: tool.schema.string().nullable().optional(),',
        '  talDraftId: tool.schema.string().optional(),',
        '  talDraftRef: tool.schema.string().optional(),',
        '  talDraft: draftBlueprintSchema.optional(),',
        '  addDanceUrns: optionalStringArray,',
        '  addDanceDraftIds: optionalStringArray,',
        '  addDanceDraftRefs: optionalStringArray,',
        '  addDanceDrafts: tool.schema.array(draftBlueprintSchema).optional(),',
        '  removeDanceUrns: optionalStringArray,',
        '  removeDanceDraftIds: optionalStringArray,',
        '  addMcpServerNames: optionalStringArray,',
        '  removeMcpServerNames: optionalStringArray,',
        '}',
        'const locatorFields = {',
        '  actId: tool.schema.string().optional(),',
        '  actRef: tool.schema.string().optional(),',
        '  actName: tool.schema.string().optional(),',
        '}',
        'const performerLocatorFields = {',
        '  performerId: tool.schema.string().optional(),',
        '  performerRef: tool.schema.string().optional(),',
        '  performerName: tool.schema.string().optional(),',
        '}',
        'const actionSchema = tool.schema.discriminatedUnion("type", [',
        '  tool.schema.object({ type: tool.schema.literal("installRegistryAsset"), urn: tool.schema.string(), scope: tool.schema.enum(["global", "stage"]).optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("addDanceFromGitHub"), source: tool.schema.string(), scope: tool.schema.enum(["global", "stage"]).optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("importInstalledPerformer"), urn: tool.schema.string().optional(), performerName: tool.schema.string().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("importInstalledAct"), urn: tool.schema.string().optional(), actName: tool.schema.string().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("createTalDraft"), ref: tool.schema.string().optional(), name: tool.schema.string(), content: tool.schema.string(), slug: tool.schema.string().optional(), description: tool.schema.string().optional(), tags: optionalStringArray, openEditor: tool.schema.boolean().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("updateTalDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), name: tool.schema.string().optional(), content: tool.schema.string().optional(), description: tool.schema.string().optional(), tags: optionalStringArray }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteTalDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("createDanceDraft"), ref: tool.schema.string().optional(), name: tool.schema.string(), content: tool.schema.string(), slug: tool.schema.string().optional(), description: tool.schema.string().optional(), tags: optionalStringArray, openEditor: tool.schema.boolean().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("updateDanceDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), name: tool.schema.string().optional(), content: tool.schema.string().optional(), description: tool.schema.string().optional(), tags: optionalStringArray }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteDanceDraft"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("upsertDanceBundleFile"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), path: tool.schema.string().refine((value) => normalizeAssistantBundlePath(value) !== null, "Bundle path must stay within the draft bundle."), content: tool.schema.string() }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteDanceBundleEntry"), draftId: tool.schema.string().optional(), draftRef: tool.schema.string().optional(), draftName: tool.schema.string().optional(), path: tool.schema.string().refine((value) => normalizeAssistantBundlePath(value) !== null, "Bundle path must stay within the draft bundle.") }),',
        '  tool.schema.object({ type: tool.schema.literal("createPerformer"), ref: tool.schema.string().optional(), name: tool.schema.string(), ...performerFieldsSchema }),',
        '  tool.schema.object({ type: tool.schema.literal("updatePerformer"), ...performerLocatorFields, name: tool.schema.string().optional(), ...performerFieldsSchema }),',
        '  tool.schema.object({ type: tool.schema.literal("deletePerformer"), ...performerLocatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("createAct"), ref: tool.schema.string().optional(), name: tool.schema.string(), description: tool.schema.string().optional(), actRules: optionalStringArray, safety: safetySchema.optional(), participantPerformerIds: optionalStringArray, participantPerformerRefs: optionalStringArray, participantPerformerNames: optionalStringArray, relations: tool.schema.array(relationBlueprintSchema).optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("updateAct"), ...locatorFields, name: tool.schema.string().optional(), description: tool.schema.string().optional(), actRules: optionalStringArray, safety: safetySchema.nullable().optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("deleteAct"), ...locatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("attachPerformerToAct"), ...locatorFields, ...performerLocatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("detachParticipantFromAct"), ...locatorFields, participantKey: tool.schema.string().optional(), ...performerLocatorFields }),',
        '  tool.schema.object({ type: tool.schema.literal("updateParticipantSubscriptions"), ...locatorFields, participantKey: tool.schema.string().optional(), ...performerLocatorFields, subscriptions: subscriptionsSchema.nullable() }),',
        '  tool.schema.object({ type: tool.schema.literal("connectPerformers"), ...locatorFields, sourceParticipantKey: tool.schema.string().optional(), sourcePerformerId: tool.schema.string().optional(), sourcePerformerRef: tool.schema.string().optional(), sourcePerformerName: tool.schema.string().optional(), targetParticipantKey: tool.schema.string().optional(), targetPerformerId: tool.schema.string().optional(), targetPerformerRef: tool.schema.string().optional(), targetPerformerName: tool.schema.string().optional(), direction: tool.schema.enum(["both", "one-way"]).optional(), name: tool.schema.string(), description: tool.schema.string() }),',
        '  tool.schema.object({ type: tool.schema.literal("updateRelation"), ...locatorFields, relationId: tool.schema.string(), name: tool.schema.string().optional(), description: tool.schema.string().optional(), direction: tool.schema.enum(["both", "one-way"]).optional() }),',
        '  tool.schema.object({ type: tool.schema.literal("removeRelation"), ...locatorFields, relationId: tool.schema.string() }),',
        '])',
        '',
        'export default tool({',
        '  description: "Apply Studio workspace mutations. Use this tool instead of pasting raw mutation JSON into the assistant reply. Call it only when the user explicitly wants Studio canvas or draft changes.",',
        '  args: {',
        '    version: tool.schema.literal(1).describe("Assistant action envelope version."),',
        '    actions: tool.schema.array(actionSchema).min(1).describe("Ordered Studio mutation actions to apply in Studio. Keep dependent actions in execution order."),',
        '  },',
        '  async execute(args, context) {',
        '    const normalizedArgs = normalizeAssistantActionEnvelope(args)',
        '    const lintIssues = lintAssistantActionEnvelope(normalizedArgs)',
        '    const lintErrors = lintIssues.filter((issue) => issue.level === "error")',
        '    if (lintErrors.length > 0) {',
        '      throw new Error([',
        '        "apply_studio_actions rejected the mutation envelope.",',
        '        ...lintErrors.map((issue) => `- action #${issue.actionIndex + 1}: ${issue.message}`),',
        '      ].join("\\n"))',
        '    }',
        '    const lintWarnings = lintIssues.filter((issue) => issue.level === "warning")',
        '    const count = Array.isArray(normalizedArgs.actions) ? normalizedArgs.actions.length : 0',
        '    context.metadata({',
        '      title: count === 1 ? "Apply Studio change" : `Apply ${count} Studio changes`,',
        '      metadata: {',
        '        studioAssistantMutation: true,',
        '        studioActionCount: count,',
        '        studioLintWarnings: lintWarnings.map((issue) => ({',
        '          actionIndex: issue.actionIndex,',
        '          message: issue.message,',
        '        })),',
        '      },',
        '    })',
        '    return count === 1',
        '      ? "Queued 1 Studio change for Studio to apply."',
        '      : `Queued ${count} Studio changes for Studio to apply.`',
        '  },',
        '})',
        '',
    ].join('\n')
}

export function getStaticAssistantTools(): Array<{ name: string; content: string }> {
    return [{
        name: ASSISTANT_MUTATION_TOOL_NAME,
        content: buildAssistantMutationToolContent(),
    }]
}
